// Generated by CoffeeScript 1.8.0
(function() {
  angular.module('app').factory('tag.service', [
    'rcolor', function(rcolor) {
      var tagService;
      return new (tagService = (function() {
        var _getTagColor, _userTags, _userTagsContains;

        function tagService() {}

        _userTags = [];

        _getTagColor = function(tagText) {
          var tag, tg;
          tag = (function() {
            var _i, _len, _results;
            _results = [];
            for (_i = 0, _len = _userTags.length; _i < _len; _i++) {
              tg = _userTags[_i];
              if (tg.text === tagText) {
                _results.push(tg);
              }
            }
            return _results;
          })();
          if (tag.length && tag[0].color) {
            return tag[0].color;
          } else {
            return rcolor.get();
          }
        };

        _userTagsContains = function(tag) {
          var t, _i, _len;
          for (_i = 0, _len = _userTags.length; _i < _len; _i++) {
            t = _userTags[_i];
            if (t.text === tag.text) {
              return true;
            }
          }
        };

        tagService.prototype.colorAndSaveTags = function(tags) {
          var tag, text, _i, _len, _results;
          if (!tags) {
            return;
          }
          _results = [];
          for (_i = 0, _len = tags.length; _i < _len; _i++) {
            tag = tags[_i];
            if (tag.text) {
              tag.color = _getTagColor(tag.text);
            } else {
              text = tag;
              tag = {
                text: text,
                color: _getTagColor(text)
              };
            }
            if (!_userTagsContains(tag)) {
              _userTags.push(angular.copy(tag));
            }
            _results.push(tag);
          }
          return _results;
        };

        tagService.prototype.getTagColorStyle = function(color) {
          return 'transparent ' + color + ' transparent transparent';
        };

        tagService.prototype.getUserTags = function() {
          return _userTags;
        };

        return tagService;

      })());
    }
  ]);

}).call(this);

//# sourceMappingURL=tag.service.js.map
