// Generated by CoffeeScript 1.8.0
(function() {
  angular.module('app').factory('tagstats.service', [
    'tag.service', 'common', 'datacontext', function(tagService, common, datacontext) {
      var tagStatsService;
      return new (tagStatsService = (function() {
        var maxBarWidth, ratio;

        function tagStatsService() {}

        maxBarWidth = 290;

        ratio = 1;

        tagStatsService.prototype.getBarWidth = function(percent) {
          return ((percent / 100) * maxBarWidth) * ratio + 'px';
        };

        tagStatsService.prototype.getTagStats = function(min, max, includeTags, excludeTags) {
          var def;
          def = common.defer();
          datacontext.getTagsExpenses(min, max, includeTags, excludeTags).success(function(data) {
            var longestBar, maxPercent, stats, tagstat, _i, _len;
            stats = data.slice(0, 11);
            maxPercent = (stats.reduce(function(a, b) {
              if (a.percent > b.percent) {
                return a;
              } else {
                return b;
              }
            })).percent;
            longestBar = (maxPercent / 100) * maxBarWidth;
            ratio = maxBarWidth / longestBar;
            for (_i = 0, _len = stats.length; _i < _len; _i++) {
              tagstat = stats[_i];
              tagstat.tags = tagService.colorAndSaveTags(tagstat.tags);
            }
            console.log(stats);
            return def.resolve(stats);
          }).error(function() {
            return def.reject();
          });
          return def.promise;
        };

        return tagStatsService;

      })());
    }
  ]);

}).call(this);

//# sourceMappingURL=tagstats.service.js.map
