// Generated by CoffeeScript 1.8.0
(function() {
  var __slice = [].slice;

  this.BaseCtrl = (function() {
    var getName;

    function BaseCtrl(common) {
      this.common = common;
    }

    getName = function(fun) {
      var ret;
      ret = fun.toString();
      ret = ret.substr('function '.length);
      return ret.substr(0, ret.indexOf('('));
    };

    BaseCtrl.prototype.activate = function(promises) {
      return this.common.activateController(promises, getName(this.constructor)).then(function() {
        return console.log('activated ' + getName(this.constructor));
      });
    };

    BaseCtrl.register = function(moduleName) {
      if (moduleName == null) {
        moduleName = 'app';
      }
      return angular.module(moduleName).controller(getName(this), this);
    };

    BaseCtrl.inject = function() {
      var args;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return this.$inject = args;
    };

    return BaseCtrl;

  })();

}).call(this);

//# sourceMappingURL=baseController.js.map
